# Generated by Django 4.2.11 on 2025-06-16 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("openRoute_app", "0002_country_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="place_type",
            field=models.CharField(
                choices=[
                    ("R", "Restaurant"),
                    ("H", "Hotel"),
                    ("A", "Attraction"),
                    ("S", "Shopping"),
                    ("T", "Theatre"),
                    ("CI", "Cinema"),
                    ("Ba", "Bar"),
                    ("CL", "Club"),
                    ("G", "Gallery"),
                    ("L", "Library"),
                    ("Z", "Zoo"),
                    ("AQ", "Aquarium"),
                    ("Be", "Beach"),
                    ("TP", "Theme Park"),
                    ("M", "Museum"),
                    ("P", "Park"),
                    ("O", "Other"),
                ],
                default="O",
                max_length=2,
            ),
        ),
    ]
